Repository skills/secure-code-game, pull requests merged in 2023-04, with the labels that each got.

#23 Re-order local installation steps
  README.md
Labels: documentation

#26 Update hack.py
  Level-3/hack.py
Labels: enhancement

#27 Fix "invalid salt" issue in level 5 (#18)
  Level-5/code.py
  Level-5/solution.py
Labels: bug
